### ISSUE TITLE
Pretrained backbone weights

### ISSUE THREAD

**Issue by tanveer6715** [jiaowoguanren0615/SegFormer-Pytorch#1]
Hi,
Thanks for providing code. However I couldnt find pretrained weights like for B0 to B5. How to add htese pretrained weights and train the SegFormer?

**Comment by jiaowoguanren0615** [comment]
Sure, you can download the pretrained-weights in this url: https://github.com/NVlabs/SegFormer

**Comment by tanveer6715** [comment]
Thanks for your response. I mean to say that suppose I have pretrained weights of mit-B5 then how I can use it for SegFormer B5 model?

**Comment by jiaowoguanren0615** [comment]
You can add code in the **_SegFormer_** Class, for the variable of **_self.mit_**, you can _**add a parameter "pretrain_path"**_, set it to your pretrained weights path, and load weights. However, you should notice that there are not entire layers in self.mit, for example: **_there is no cls-head layer, So I recommend you use "if else" judge each layer, which can ensure that you can load all matched layers successfully._**

**Comment by tanveer6715** [comment]
Thank you.
